name: Auto Merge PR After Approval

on:
  pull_request_review:
    types:
      - submitted

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "${{ secrets.GIT_COMMIT_AUTHOR_EMAIL }}"
          git config user.name "${{ secrets.GIT_COMMIT_AUTHOR_NAME }}"

      - name: Merge PR on Approval
        if: github.event.review.state == 'approved'
        run: |
          git fetch
          git checkout ${{ github.event.pull_request.base.ref }}
          git merge --no-ff --no-commit ${{ github.event.pull_request.head.sha }}
          git commit -m "Merge pull request #${{ github.event.pull_request.number }}"

          # Push changes to the same branch
          git push origin ${{ github.event.pull_request.base.ref }}

      - name: Delete Branch
        run: |
          # Fetch all branches to make sure we have the latest information
          git fetch --all

          # Get the branch name
          branch_name="${{ github.event.pull_request.head.ref }}"

          # Check if the branch exists before deleting
          if git rev-parse --verify "refs/remotes/origin/${branch_name}"; then
            echo "Deleting branch: ${branch_name}"
            git push origin --delete "${branch_name}"
          else
            echo "Branch does not exist, no action needed."
          fi
